### ISSUE TITLE
[Enhancement] Change "Désactiver" into "Désactiver le salon" for `/config disabled-channels`

### ISSUE THREAD

**Issue by anhgelus** [anhgelus/les-copaings-bot#4]
"Désactiver" is confusing, "Désactiver le salon " is not confusing. It's easier to understand what it does with this modification.

We must do the same for "Activer".

**Comment by Flydexo** [comment]
Hi, saw your video on Youtube. Interested to contribute. I'm a bit lost, is the bot in french or in english? Because you write in english on github while having feature names in french?

**Comment by anhgelus** [comment]
Fixed
